const rouleauFour1 = {
    moteur:"Rouleau Four 1",

    contactAuxiliaire: "Arp.Plc.Eclr/disjServoFours",
    RDMContacteur: "Arp.Plc.Eclr/RDMServoRouleauxFours",
    erreurDisjoncteur: "Arp.Plc.Eclr/erreurDisjoncteurRouleauxFours",
    erreurContacteur: "Arp.Plc.Eclr/erreurContacteurRouleauxFours",

    axisControlEnable: "Arp.Plc.Eclr/startRouleauFour1",
    axisControlAlarmClear: "Arp.Plc.Eclr/acquitterRouleauFour1",
    axisControlStatus: "Arp.Plc.Eclr/axisControlOutRouleauFour1.Status",
    axisControlAxisAlarm: "Arp.Plc.Eclr/axisControlOutRouleauFour1.AxisAlarm",
    axisControlDriveWarning: "Arp.Plc.Eclr/axisControlOutRouleauFour1.DriveWarning",
    axisControlError: "Arp.Plc.Eclr/axisControlOutRouleauFour1.Error",
    axisControlErrorID: "Arp.Plc.Eclr/axisControlOutRouleauFour1.ErrorID",
    axisControlDriveWarningID: "Arp.Plc.Eclr/axisControlOutRouleauFour1.DriveWarningID",
    axisControlDriveAlarmID: "Arp.Plc.Eclr/axisControlOutRouleauFour1.DriveAlarmID",
    axisControlControlAlarmID: "Arp.Plc.Eclr/axisControlOutRouleauFour1.ControlAlarmID",

    statusValid: "Arp.Plc.Eclr/axisStatusRouleauFour1.Valid",
    statusBusy: "Arp.Plc.Eclr/axisStatusRouleauFour1.Busy",
    statusErrorStop: "Arp.Plc.Eclr/axisStatusRouleauFour1.ErrorStop",
    statusConstantVelocity: "Arp.Plc.Eclr/axisStatusRouleauFour1.ConstantVelocity",
    statusAccelerating: "Arp.Plc.Eclr/axisStatusRouleauFour1.Accelerating",
    statusDecelerating: "Arp.Plc.Eclr/axisStatusRouleauFour1.Decelerating",
    statusError: "Arp.Plc.Eclr/axisStatusRouleauFour1.Error",
    statusErrorID: "Arp.Plc.Eclr/axisStatusRouleauFour1.ErrorID",
    statusDisable: "Arp.Plc.Eclr/axisStatusRouleauFour1.Disable",
    statusStopping: "Arp.Plc.Eclr/axisStatusRouleauFour1.Stopping",
    statusStandStill: "Arp.Plc.Eclr/axisStatusRouleauFour1.StandStill",
    statusDiscreteMotion: "Arp.Plc.Eclr/axisStatusRouleauFour1.DiscreteMotion",
    statusContinuousMotion: "Arp.Plc.Eclr/axisStatusRouleauFour1.ContinuousMotion",
    statusSynchronizedMotion: "Arp.Plc.Eclr/axisStatusRouleauFour1.SynchronizedMotion",
    statusHoming: "Arp.Plc.Eclr/axisStatusRouleauFour1.Homing",

    gearInExecute:"",
    gearInRatioNumerator: "Arp.Plc.Eclr/ratioRouleauFour1",
    gearInVelocity:"",
    gearInAcceleration: "Arp.Plc.Eclr/accelerationMaitreFour1",
    gearInDeceleration: "Arp.Plc.Eclr/decelerationMaitreFour1",
    gearInInGear: "Arp.Plc.Eclr/gearInOutRouleauFour1.InGear",
    gearInBusy: "Arp.Plc.Eclr/gearInOutRouleauFour1.Busy",
    gearInActive: "Arp.Plc.Eclr/gearInOutRouleauFour1.Active",
    gearInCommandAborted: "Arp.Plc.Eclr/gearInOutRouleauFour1.CommandAborted",
    gearInError: "Arp.Plc.Eclr/gearInOutRouleauFour1.Error",
    gearInErrorID: "Arp.Plc.Eclr/gearInOutRouleauFour1.ErrorID",

    gearOutExecute:"",
    gearOutDone: "Arp.Plc.Eclr/gearOutOutRouleauFour1.Done",
    gearOutBusy: "Arp.Plc.Eclr/gearOutOutRouleauFour1.Busy",
    gearOutError: "Arp.Plc.Eclr/gearOutOutRouleauFour1.Error",
    gearOutErrorID: "Arp.Plc.Eclr/gearOutOutRouleauFour1.ErrorID",

    jogForward: "",
    jogReverse: "Arp.Plc.Eclr/reverseManuelRouleauFour1",
    jogVelocity: "Arp.Plc.Eclr/vitesseManuelRouleauFour1",
    jogAcceleration: "Arp.Plc.Eclr/accelerationManuelRouleauFour1",
    jogDeceleration: "Arp.Plc.Eclr/decelerationManuelRouleauFour1",
    jogInVelocity: "Arp.Plc.Eclr/jogOutRouleauFour1.InVelocity",
    jogDone: "Arp.Plc.Eclr/jogOutRouleauFour1.Done",
    jogBusy: "Arp.Plc.Eclr/jogOutRouleauFour1.Busy",
    jogError: "Arp.Plc.Eclr/jogOutRouleauFour1.Error",
    jogErrorID: "Arp.Plc.Eclr/jogOutRouleauFour1.ErrorID",

    resetAxisExecute: "Arp.Plc.Eclr/resetAxisRouleauFour1",
    resetAxisDone: "Arp.Plc.Eclr/resetAxisOutRouleauFour1.Done",
    resetAxisBusy: "Arp.Plc.Eclr/resetAxisOutRouleauFour1.Busy",
    resetAxisError: "Arp.Plc.Eclr/resetAxisOutRouleauFour1.Error",
    resetAxisErrorID: "Arp.Plc.Eclr/resetAxisOutRouleauFour1.ErrorID",

    resetEncodeurExecute: "Arp.Plc.Eclr/resetEncodeurRouleauFour1",
    resetEncodeurDone: "Arp.Plc.Eclr/resetEncodeurOutRouleauFour1.Done",
    resetEncodeurBusy: "Arp.Plc.Eclr/resetEncodeurOutRouleauFour1.Busy",
    resetEncodeurError: "Arp.Plc.Eclr/resetEncodeurOutRouleauFour1.Error",
    resetEncodeurErrorID: "Arp.Plc.Eclr/resetEncodeurOutRouleauFour1.ErrorID",

    stopAxisExecute: "Arp.Plc.Eclr/stopAxisRouleauFour1",
    stopAxisDone: "Arp.Plc.Eclr/stopOutputRouleauFour1.Done",
    stopAxisBusy: "Arp.Plc.Eclr/stopOutputRouleauFour1.Busy",
    stopAxisActive: "Arp.Plc.Eclr/stopOutputRouleauFour1.Active",
    stopAxisCommandAborted: "Arp.Plc.Eclr/stopOutputRouleauFour1.CommandAborted",
    stopAxisError: "Arp.Plc.Eclr/stopOutputRouleauFour1.Error",
    stopAxisErrorID: "Arp.Plc.Eclr/stopOutputRouleauFour1.ErrorID",

    rebootServoExecute: "Arp.Plc.Eclr/rebootServoRouleauFour1",
    rebootServoDone: "Arp.Plc.Eclr/rebootServoOutRouleauFour1.Done",
    rebootServoBusy: "Arp.Plc.Eclr/rebootServoOutRouleauFour1.Busy",
    rebootServoError: "Arp.Plc.Eclr/rebootServoOutRouleauFour1.Error",
    rebootServoErrorID: "Arp.Plc.Eclr/rebootServoOutRouleauFour1.ErrorID",

    valuePosition: "Arp.Plc.Eclr/axisValueRouleauFour1.Position",
    valueTorque: "Arp.Plc.Eclr/axisValueRouleauFour1.Torque",
    valueVelocity: "Arp.Plc.Eclr/axisValueRouleauFour1.Velocity",

}

const deposeFilsFour1 = {
    moteur:"Depose Fils Four 1",

    contactAuxiliaire: "Arp.Plc.Eclr/disjServoFours",
    RDMContacteur: "Arp.Plc.Eclr/RDMServoDeposeFilsFours",
    erreurDisjoncteur: "Arp.Plc.Eclr/erreurDisjoncteurDeposeFilsFours",
    erreurContacteur: "Arp.Plc.Eclr/erreurContacteurDeposeFilsFours",

    axisControlEnable: "Arp.Plc.Eclr/startDeposeFilsFour1",
    axisControlAlarmClear: "Arp.Plc.Eclr/acquitterDeposeFilsFour1",
    axisControlStatus: "Arp.Plc.Eclr/axisControlOutDeposeFilsFour1.Status",
    axisControlAxisAlarm: "Arp.Plc.Eclr/axisControlOutDeposeFilsFour1.AxisAlarm",
    axisControlDriveWarning: "Arp.Plc.Eclr/axisControlOutDeposeFilsFour1.DriveWarning",
    axisControlError: "Arp.Plc.Eclr/axisControlOutDeposeFilsFour1.Error",
    axisControlErrorID: "Arp.Plc.Eclr/axisControlOutDeposeFilsFour1.ErrorID",
    axisControlDriveWarningID: "Arp.Plc.Eclr/axisControlOutDeposeFilsFour1.DriveWarningID",
    axisControlDriveAlarmID: "Arp.Plc.Eclr/axisControlOutDeposeFilsFour1.DriveAlarmID",
    axisControlControlAlarmID: "Arp.Plc.Eclr/axisControlOutDeposeFilsFour1.ControlAlarmID",

    statusValid: "Arp.Plc.Eclr/axisStatusDeposeFilsFour1.Valid",
    statusBusy: "Arp.Plc.Eclr/axisStatusDeposeFilsFour1.Busy",
    statusErrorStop: "Arp.Plc.Eclr/axisStatusDeposeFilsFour1.ErrorStop",
    statusConstantVelocity: "Arp.Plc.Eclr/axisStatusDeposeFilsFour1.ConstantVelocity",
    statusAccelerating: "Arp.Plc.Eclr/axisStatusDeposeFilsFour1.Accelerating",
    statusDecelerating: "Arp.Plc.Eclr/axisStatusDeposeFilsFour1.Decelerating",
    statusError: "Arp.Plc.Eclr/axisStatusDeposeFilsFour1.Error",
    statusErrorID: "Arp.Plc.Eclr/axisStatusDeposeFilsFour1.ErrorID",
    statusDisable: "Arp.Plc.Eclr/axisStatusDeposeFilsFour1.Disable",
    statusStopping: "Arp.Plc.Eclr/axisStatusDeposeFilsFour1.Stopping",
    statusStandStill: "Arp.Plc.Eclr/axisStatusDeposeFilsFour1.StandStill",
    statusDiscreteMotion: "Arp.Plc.Eclr/axisStatusDeposeFilsFour1.DiscreteMotion",
    statusContinuousMotion: "Arp.Plc.Eclr/axisStatusDeposeFilsFour1.ContinuousMotion",
    statusSynchronizedMotion: "Arp.Plc.Eclr/axisStatusDeposeFilsFour1.SynchronizedMotion",
    statusHoming: "Arp.Plc.Eclr/axisStatusDeposeFilsFour1.Homing",

    gearInExecute:"",
    gearInRatioNumerator:"Arp.Plc.Eclr/ratioDeposeFilsFour1",
    gearInVelocity:"",
    gearInAcceleration:"Arp.Plc.Eclr/accelerationMaitreFour1",
    gearInDeceleration:"Arp.Plc.Eclr/decelerationMaitreFour1",
    gearInInGear:"Arp.Plc.Eclr/gearInOutDeposeFilsFour1.InGear",
    gearInBusy:"Arp.Plc.Eclr/gearInOutDeposeFilsFour1.Busy",
    gearInActive:"Arp.Plc.Eclr/gearInOutDeposeFilsFour1.Active",
    gearInCommandAborted:"Arp.Plc.Eclr/gearInOutDeposeFilsFour1.CommandAborted",
    gearInError:"Arp.Plc.Eclr/gearInOutDeposeFilsFour1.Error",
    gearInErrorID:"Arp.Plc.Eclr/gearInOutDeposeFilsFour1.ErrorID",

    gearOutExecute: "",
    gearOutDone: "Arp.Plc.Eclr/gearOutOutDeposeFilsFour1.Done",
    gearOutBusy: "Arp.Plc.Eclr/gearOutOutDeposeFilsFour1.Busy",
    gearOutError: "Arp.Plc.Eclr/gearOutOutDeposeFilsFour1.Error",
    gearOutErrorID: "Arp.Plc.Eclr/gearOutOutDeposeFilsFour1.ErrorID",

    jogForward:"",
    jogReverse: "Arp.Plc.Eclr/reverseManuelDeposeFilsFour1",
    jogVelocity: "Arp.Plc.Eclr/vitesseManuelDeposeFilsFour1",
    jogAcceleration: "Arp.Plc.Eclr/accelerationManuelDeposeFilsFour1",
    jogDeceleration: "Arp.Plc.Eclr/decelerationManuelDeposeFilsFour1",
    jogInVelocity: "Arp.Plc.Eclr/jogOutDeposeFilsFour1.InVelocity",
    jogDone: "Arp.Plc.Eclr/jogOutDeposeFilsFour1.Done",
    jogBusy: "Arp.Plc.Eclr/jogOutDeposeFilsFour1.Busy",
    jogError: "Arp.Plc.Eclr/jogOutDeposeFilsFour1.Error",
    jogErrorID: "Arp.Plc.Eclr/jogOutDeposeFilsFour1.ErrorID",

    resetAxisExecute: "Arp.Plc.Eclr/resetAxisDeposeFilsFour1",
    resetAxisDone: "Arp.Plc.Eclr/resetAxisOutDeposeFilsFour1.Done",
    resetAxisBusy: "Arp.Plc.Eclr/resetAxisOutDeposeFilsFour1.Busy",
    resetAxisError: "Arp.Plc.Eclr/resetAxisOutDeposeFilsFour1.Error",
    resetAxisErrorID: "Arp.Plc.Eclr/resetAxisOutDeposeFilsFour1.ErrorID",

    resetEncodeurExecute:"Arp.Plc.Eclr/resetEncodeurDeposeFilsFour1",
    resetEncodeurDone:"Arp.Plc.Eclr/resetEncodeurOutDeposeFilsFour1.Done",
    resetEncodeurBusy:"Arp.Plc.Eclr/resetEncodeurOutDeposeFilsFour1.Busy",
    resetEncodeurError:"Arp.Plc.Eclr/resetEncodeurOutDeposeFilsFour1.Error",
    resetEncodeurErrorID:"Arp.Plc.Eclr/resetEncodeurOutDeposeFilsFour1.ErrorID",

    stopAxisExecute: "Arp.Plc.Eclr/stopAxisDeposeFilsFour1",
    stopAxisDone: "Arp.Plc.Eclr/stopOutputDeposeFilsFour1.Done",
    stopAxisBusy: "Arp.Plc.Eclr/stopOutputDeposeFilsFour1.Busy",
    stopAxisActive: "Arp.Plc.Eclr/stopOutputDeposeFilsFour1.Active",
    stopAxisCommandAborted: "Arp.Plc.Eclr/stopOutputDeposeFilsFour1.CommandAborted",
    stopAxisError: "Arp.Plc.Eclr/stopOutputDeposeFilsFour1.Error",
    stopAxisErrorID: "Arp.Plc.Eclr/stopOutputDeposeFilsFour1.ErrorID",

    rebootServoExecute: "Arp.Plc.Eclr/rebootServoDeposeFilsFour1",
    rebootServoDone: "Arp.Plc.Eclr/rebootServoOutDeposeFilsFour1.Done",
    rebootServoBusy: "Arp.Plc.Eclr/rebootServoOutDeposeFilsFour1.Busy",
    rebootServoError: "Arp.Plc.Eclr/rebootServoOutDeposeFilsFour1.Error",
    rebootServoErrorID: "Arp.Plc.Eclr/rebootServoOutDeposeFilsFour1.ErrorID",

    valuePosition: "Arp.Plc.Eclr/axisValueDeposeFilsFour1.Position",
    valueTorque: "Arp.Plc.Eclr/axisValueDeposeFilsFour1.Torque",
    valueVelocity: "Arp.Plc.Eclr/axisValueDeposeFilsFour1.Velocity",
}

const tapisFour1 = {
    moteur:"Tapis Four 1",

    contactAuxiliaire: "Arp.Plc.Eclr/disjServoFours",
    RDMContacteur: "Arp.Plc.Eclr/RDMServoTapisFours",
    erreurDisjoncteur: "Arp.Plc.Eclr/erreurDisjoncteurTapisFours",
    erreurContacteur: "Arp.Plc.Eclr/erreurContacteurTapisFours",

    axisControlEnable:"Arp.Plc.Eclr/startTapisFour1",
    axisControlAlarmClear:"Arp.Plc.Eclr/acquitterTapisFour1",
    axisControlStatus:"Arp.Plc.Eclr/axisControlOutTapisFour1.Status",
    axisControlAxisAlarm:"Arp.Plc.Eclr/axisControlOutTapisFour1.AxisAlarm",
    axisControlDriveWarning:"Arp.Plc.Eclr/axisControlOutTapisFour1.DriveWarning",
    axisControlError:"Arp.Plc.Eclr/axisControlOutTapisFour1.Error",
    axisControlErrorID:"Arp.Plc.Eclr/axisControlOutTapisFour1.ErrorID",
    axisControlDriveWarningID:"Arp.Plc.Eclr/axisControlOutTapisFour1.DriveWarningID",
    axisControlDriveAlarmID:"Arp.Plc.Eclr/axisControlOutTapisFour1.DriveAlarmID",
    axisControlControlAlarmID:"Arp.Plc.Eclr/axisControlOutTapisFour1.ControlAlarmID",

    statusValid:"Arp.Plc.Eclr/axisStatusTapisFour1.Valid",
    statusBusy:"Arp.Plc.Eclr/axisStatusTapisFour1.Busy",
    statusErrorStop:"Arp.Plc.Eclr/axisStatusTapisFour1.ErrorStop",
    statusConstantVelocity:"Arp.Plc.Eclr/axisStatusTapisFour1.ConstantVelocity",
    statusAccelerating:"Arp.Plc.Eclr/axisStatusTapisFour1.Accelerating",
    statusDecelerating:"Arp.Plc.Eclr/axisStatusTapisFour1.Decelerating",
    statusError:"Arp.Plc.Eclr/axisStatusTapisFour1.Error",
    statusErrorID:"Arp.Plc.Eclr/axisStatusTapisFour1.ErrorID",
    statusDisable:"Arp.Plc.Eclr/axisStatusTapisFour1.Disable",
    statusStopping:"Arp.Plc.Eclr/axisStatusTapisFour1.Stopping",
    statusStandStill:"Arp.Plc.Eclr/axisStatusTapisFour1.StandStill",
    statusDiscreteMotion:"Arp.Plc.Eclr/axisStatusTapisFour1.DiscreteMotion",
    statusContinuousMotion:"Arp.Plc.Eclr/axisStatusTapisFour1.ContinuousMotion",
    statusSynchronizedMotion:"Arp.Plc.Eclr/axisStatusTapisFour1.SynchronizedMotion",
    statusHoming:"Arp.Plc.Eclr/axisStatusTapisFour1.Homing",

    gearInExecute:"",
    gearInRatioNumerator:"Arp.Plc.Eclr/ratioTapisFour1",
    gearInVelocity:"",
    gearInAcceleration:"Arp.Plc.Eclr/accelerationMaitreFour1",
    gearInDeceleration:"Arp.Plc.Eclr/decelerationMaitreFour1",
    gearInInGear:"Arp.Plc.Eclr/gearInOutTapisFour1.InGear",
    gearInBusy:"Arp.Plc.Eclr/gearInOutTapisFour1.Busy",
    gearInActive:"Arp.Plc.Eclr/gearInOutTapisFour1.Active",
    gearInCommandAborted:"Arp.Plc.Eclr/gearInOutTapisFour1.CommandAborted",
    gearInError:"Arp.Plc.Eclr/gearInOutTapisFour1.Error",
    gearInErrorID:"Arp.Plc.Eclr/gearInOutTapisFour1.ErrorID",

    gearOutExecute:"",
    gearOutDone:"Arp.Plc.Eclr/gearOutOutTapisFour1.Done",
    gearOutBusy:"Arp.Plc.Eclr/gearOutOutTapisFour1.Busy",
    gearOutError:"Arp.Plc.Eclr/gearOutOutTapisFour1.Error",
    gearOutErrorID:"Arp.Plc.Eclr/gearOutOutTapisFour1.ErrorID",

    jogForward:"",
    jogReverse:"Arp.Plc.Eclr/reverseManuelTapisFour1",
    jogVelocity:"Arp.Plc.Eclr/vitesseManuelTapisFour1",
    jogAcceleration:"Arp.Plc.Eclr/accelerationManuelTapisFour1",
    jogDeceleration:"Arp.Plc.Eclr/decelerationManuelTapisFour1",
    jogInVelocity:"Arp.Plc.Eclr/jogOutTapisFour1.InVelocity",
    jogDone:"Arp.Plc.Eclr/jogOutTapisFour1.Done",
    jogBusy:"Arp.Plc.Eclr/jogOutTapisFour1.Busy",
    jogError:"Arp.Plc.Eclr/jogOutTapisFour1.Error",
    jogErrorID:"Arp.Plc.Eclr/jogOutTapisFour1.ErrorID",

    resetAxisExecute:"Arp.Plc.Eclr/resetAxisTapisFour1",
    resetAxisDone:"Arp.Plc.Eclr/resetAxisOutTapisFour1.Done",
    resetAxisBusy:"Arp.Plc.Eclr/resetAxisOutTapisFour1.Busy",
    resetAxisError:"Arp.Plc.Eclr/resetAxisOutTapisFour1.Error",
    resetAxisErrorID:"Arp.Plc.Eclr/resetAxisOutTapisFour1.ErrorID",

    resetEncodeurExecute:"Arp.Plc.Eclr/resetEncodeurTapisFour1",
    resetEncodeurDone:"Arp.Plc.Eclr/resetEncodeurOutTapisFour1.Done",
    resetEncodeurBusy:"Arp.Plc.Eclr/resetEncodeurOutTapisFour1.Busy",
    resetEncodeurError:"Arp.Plc.Eclr/resetEncodeurOutTapisFour1.Error",
    resetEncodeurErrorID:"Arp.Plc.Eclr/resetEncodeurOutTapisFour1.ErrorID",

    stopAxisExecute:"Arp.Plc.Eclr/stopAxisTapisFour1",
    stopAxisDone:"Arp.Plc.Eclr/stopOutputTapisFour1.Done",
    stopAxisBusy:"Arp.Plc.Eclr/stopOutputTapisFour1.Busy",
    stopAxisActive:"Arp.Plc.Eclr/stopOutputTapisFour1.Active",
    stopAxisCommandAborted:"Arp.Plc.Eclr/stopOutputTapisFour1.CommandAborted",
    stopAxisError:"Arp.Plc.Eclr/stopOutputTapisFour1.Error",
    stopAxisErrorID:"Arp.Plc.Eclr/stopOutputTapisFour1.ErrorID",

    rebootServoExecute:"Arp.Plc.Eclr/rebootServoTapisFour1",
    rebootServoDone:"Arp.Plc.Eclr/rebootServoOutTapisFour1.Done",
    rebootServoBusy:"Arp.Plc.Eclr/rebootServoOutTapisFour1.Busy",
    rebootServoError:"Arp.Plc.Eclr/rebootServoOutTapisFour1.Error",
    rebootServoErrorID:"Arp.Plc.Eclr/rebootServoOutTapisFour1.ErrorID",

    valuePosition:"Arp.Plc.Eclr/axisValueTapisFour1.Position",
    valueTorque:"Arp.Plc.Eclr/axisValueTapisFour1.Torque",
    valueVelocity:"Arp.Plc.Eclr/axisValueTapisFour1.Velocity",
}

const preAlimenteurImpression = {
    moteur: "PreAlimenteur Impression",

    contactAuxiliaire:"Arp.Plc.Eclr/disjServoPreAlimenteursFoursIR",
    RDMContacteur:"Arp.Plc.Eclr/RDMServoPreAlimenteurFoursIR",
    erreurDisjoncteur:"Arp.Plc.Eclr/erreurDisjoncteurPreAlimenteurFoursIR",
    erreurContacteur:"Arp.Plc.Eclr/erreurContacteurPreAlimenteurFoursIR",

    axisControlEnable:"Arp.Plc.Eclr/startPreAlImpressionFoursIR",
    axisControlAlarmClear:"Arp.Plc.Eclr/acquitterPreAlImpressionFoursIR",
    axisControlStatus:"Arp.Plc.Eclr/axisControlOutPreAlimenteurImpressionFoursIR.Status",
    axisControlAxisAlarm:"Arp.Plc.Eclr/axisControlOutPreAlimenteurImpressionFoursIR.AxisAlarm",
    axisControlDriveWarning:"Arp.Plc.Eclr/axisControlOutPreAlimenteurImpressionFoursIR.DriveWarning",
    axisControlError:"Arp.Plc.Eclr/axisControlOutPreAlimenteurImpressionFoursIR.Error",
    axisControlErrorID:"Arp.Plc.Eclr/axisControlOutPreAlimenteurImpressionFoursIR.ErrorID",
    axisControlDriveWarningID:"Arp.Plc.Eclr/axisControlOutPreAlimenteurImpressionFoursIR.DriveWarningID",
    axisControlDriveAlarmID:"Arp.Plc.Eclr/axisControlOutPreAlimenteurImpressionFoursIR.DriveAlarmID",
    axisControlControlAlarmID:"Arp.Plc.Eclr/axisControlOutPreAlimenteurImpressionFoursIR.ControlAlarmID",

    statusValid:"Arp.Plc.Eclr/axisStatusPreAlimenteurImpressionFoursIR.Valid",
    statusBusy:"Arp.Plc.Eclr/axisStatusPreAlimenteurImpressionFoursIR.Busy",
    statusErrorStop:"Arp.Plc.Eclr/axisStatusPreAlimenteurImpressionFoursIR.ErrorStop",
    statusConstantVelocity:"Arp.Plc.Eclr/axisStatusPreAlimenteurImpressionFoursIR.ConstantVelocity",
    statusAccelerating:"Arp.Plc.Eclr/axisStatusPreAlimenteurImpressionFoursIR.Accelerating",
    statusDecelerating:"Arp.Plc.Eclr/axisStatusPreAlimenteurImpressionFoursIR.Decelerating",
    statusError:"Arp.Plc.Eclr/axisStatusPreAlimenteurImpressionFoursIR.Error",
    statusErrorID:"Arp.Plc.Eclr/axisStatusPreAlimenteurImpressionFoursIR.ErrorID",
    statusDisable:"Arp.Plc.Eclr/axisStatusPreAlimenteurImpressionFoursIR.Disable",
    statusStopping:"Arp.Plc.Eclr/axisStatusPreAlimenteurImpressionFoursIR.Stopping",
    statusStandStill:"Arp.Plc.Eclr/axisStatusPreAlimenteurImpressionFoursIR.StandStill",
    statusDiscreteMotion:"Arp.Plc.Eclr/axisStatusPreAlimenteurImpressionFoursIR.DiscreteMotion",
    statusContinuousMotion:"Arp.Plc.Eclr/axisStatusPreAlimenteurImpressionFoursIR.ContinuousMotion",
    statusSynchronizedMotion:"Arp.Plc.Eclr/axisStatusPreAlimenteurImpressionFoursIR.SynchronizedMotion",
    statusHoming:"Arp.Plc.Eclr/axisStatusPreAlimenteurImpressionFoursIR.Homing",

    gearInExecute:"",
    gearInRatioNumerator: "Arp.Plc.Eclr/ratioPreAlImpressionFoursIR",
    gearInVelocity:"",
    gearInAcceleration: "Arp.Plc.Eclr/accelerationMaitreFoursIR",
    gearInDeceleration: "Arp.Plc.Eclr/decelerationMaitreFoursIR",
    gearInInGear: "Arp.Plc.Eclr/gearInOutPreAlimenteurImpressionFoursIR.InGear",
    gearInBusy: "Arp.Plc.Eclr/gearInOutPreAlimenteurImpressionFoursIR.Busy",
    gearInActive: "Arp.Plc.Eclr/gearInOutPreAlimenteurImpressionFoursIR.Active",
    gearInCommandAborted: "Arp.Plc.Eclr/gearInOutPreAlimenteurImpressionFoursIR.CommandAborted",
    gearInError: "Arp.Plc.Eclr/gearInOutPreAlimenteurImpressionFoursIR.Error",
    gearInErrorID: "Arp.Plc.Eclr/gearInOutPreAlimenteurImpressionFoursIR.ErrorID",

    gearOutExecute:"",
    gearOutDone:"Arp.Plc.Eclr/gearOutOutPreAlimenteurImpressionFoursIR.Done",
    gearOutBusy:"Arp.Plc.Eclr/gearOutOutPreAlimenteurImpressionFoursIR.Busy",
    gearOutError:"Arp.Plc.Eclr/gearOutOutPreAlimenteurImpressionFoursIR.Error",
    gearOutErrorID:"Arp.Plc.Eclr/gearOutOutPreAlimenteurImpressionFoursIR.ErrorID",

    jogForward:"",
    jogReverse:"Arp.Plc.Eclr/reverseManuelPreAlImpressionFoursIR",
    jogVelocity:"Arp.Plc.Eclr/vitesseManuelPreAlImpressionFoursIR",
    jogAcceleration:"Arp.Plc.Eclr/accelerationManuelPreAlImpressionFoursIR",
    jogDeceleration:"Arp.Plc.Eclr/decelerationManuelPreAlImpressionFoursIR",
    jogInVelocity:"Arp.Plc.Eclr/jogOutPreAlimenteurImpressionFoursIR.InVelocity",
    jogDone:"Arp.Plc.Eclr/jogOutPreAlimenteurImpressionFoursIR.Done",
    jogBusy:"Arp.Plc.Eclr/jogOutPreAlimenteurImpressionFoursIR.Busy",
    jogError:"Arp.Plc.Eclr/jogOutPreAlimenteurImpressionFoursIR.Error",
    jogErrorID:"Arp.Plc.Eclr/jogOutPreAlimenteurImpressionFoursIR.ErrorID",

    resetAxisExecute:"Arp.Plc.Eclr/resetAxisPreAlImpressionFoursIR",
    resetAxisDone:"Arp.Plc.Eclr/resetAxisOutPreAlimenteurImpressionFoursIR.Done",
    resetAxisBusy:"Arp.Plc.Eclr/resetAxisOutPreAlimenteurImpressionFoursIR.Busy",
    resetAxisError:"Arp.Plc.Eclr/resetAxisOutPreAlimenteurImpressionFoursIR.Error",
    resetAxisErrorID:"Arp.Plc.Eclr/resetAxisOutPreAlimenteurImpressionFoursIR.ErrorID",

    resetEncodeurExecute:"Arp.Plc.Eclr/resetEncodeurPreAlImpressionFoursIR",
    resetEncodeurDone:"Arp.Plc.Eclr/resetEncodeurOutPreAlimenteurImpressionFoursIR.Done",
    resetEncodeurBusy:"Arp.Plc.Eclr/resetEncodeurOutPreAlimenteurImpressionFoursIR.Busy",
    resetEncodeurError:"Arp.Plc.Eclr/resetEncodeurOutPreAlimenteurImpressionFoursIR.Error",
    resetEncodeurErrorID:"Arp.Plc.Eclr/resetEncodeurOutPreAlimenteurImpressionFoursIR.ErrorID",

    stopAxisExecute:"Arp.Plc.Eclr/stopAxisPreAlImpressionFoursIR",
    stopAxisDone:"Arp.Plc.Eclr/stopOutputPreAlimenteurImpressionFoursIR.Done",
    stopAxisBusy:"Arp.Plc.Eclr/stopOutputPreAlimenteurImpressionFoursIR.Busy",
    stopAxisActive:"Arp.Plc.Eclr/stopOutputPreAlimenteurImpressionFoursIR.Active",
    stopAxisCommandAborted:"Arp.Plc.Eclr/stopOutputPreAlimenteurImpressionFoursIR.CommandAborted",
    stopAxisError:"Arp.Plc.Eclr/stopOutputPreAlimenteurImpressionFoursIR.Error",
    stopAxisErrorID:"Arp.Plc.Eclr/stopOutputPreAlimenteurImpressionFoursIR.ErrorID",

    rebootServoExecute:"Arp.Plc.Eclr/rebootServoPreAlImpressionFoursIR",
    rebootServoDone:"Arp.Plc.Eclr/rebootServoOutPreAlimenteurImpressionFoursIR.Done",
    rebootServoBusy:"Arp.Plc.Eclr/rebootServoOutPreAlimenteurImpressionFoursIR.Busy",
    rebootServoError:"Arp.Plc.Eclr/rebootServoOutPreAlimenteurImpressionFoursIR.Error",
    rebootServoErrorID:"Arp.Plc.Eclr/rebootServoOutPreAlimenteurImpressionFoursIR.ErrorID",

    valuePosition:"Arp.Plc.Eclr/axisValuePreAlimenteurImpressionFoursIR.Position",
    valueTorque:"Arp.Plc.Eclr/axisValuePreAlimenteurImpressionFoursIR.Torque",
    valueVelocity:"Arp.Plc.Eclr/axisValuePreAlimenteurImpressionFoursIR.Velocity",

}

const rouleauFoursIR = {
    moteur: "Rouleau Impression",

    contactAuxiliaire:"Arp.Plc.Eclr/disjServoRouleauFoursIR",
    RDMContacteur:"Arp.Plc.Eclr/RDMServoRouleauFoursIR",
    erreurDisjoncteur:"Arp.Plc.Eclr/erreurDisjoncteurRouleauFourIR",
    erreurContacteur:"Arp.Plc.Eclr/erreurContacteurRouleauFourIR",

    axisControlEnable:"Arp.Plc.Eclr/startRouleauFoursIR",
    axisControlAlarmClear:"Arp.Plc.Eclr/acquitterRouleauFoursIR",
    axisControlStatus:"Arp.Plc.Eclr/axisControlOutRouleauFoursIR.Status",
    axisControlAxisAlarm:"Arp.Plc.Eclr/axisControlOutRouleauFoursIR.AxisAlarm",
    axisControlDriveWarning:"Arp.Plc.Eclr/axisControlOutRouleauFoursIR.DriveWarning",
    axisControlError:"Arp.Plc.Eclr/axisControlOutRouleauFoursIR.Error",
    axisControlErrorID:"Arp.Plc.Eclr/axisControlOutRouleauFoursIR.ErrorID",
    axisControlDriveWarningID:"Arp.Plc.Eclr/axisControlOutRouleauFoursIR.DriveWarningID",
    axisControlDriveAlarmID:"Arp.Plc.Eclr/axisControlOutRouleauFoursIR.DriveAlarmID",
    axisControlControlAlarmID:"Arp.Plc.Eclr/axisControlOutRouleauFoursIR.ControlAlarmID",

    statusValid:"Arp.Plc.Eclr/axisStatusRouleauFoursIR.Valid",
    statusBusy:"Arp.Plc.Eclr/axisStatusRouleauFoursIR.Busy",
    statusErrorStop:"Arp.Plc.Eclr/axisStatusRouleauFoursIR.ErrorStop",
    statusConstantVelocity:"Arp.Plc.Eclr/axisStatusRouleauFoursIR.ConstantVelocity",
    statusAccelerating:"Arp.Plc.Eclr/axisStatusRouleauFoursIR.Accelerating",
    statusDecelerating:"Arp.Plc.Eclr/axisStatusRouleauFoursIR.Decelerating",
    statusError:"Arp.Plc.Eclr/axisStatusRouleauFoursIR.Error",
    statusErrorID:"Arp.Plc.Eclr/axisStatusRouleauFoursIR.ErrorID",
    statusDisable:"Arp.Plc.Eclr/axisStatusRouleauFoursIR.Disable",
    statusStopping:"Arp.Plc.Eclr/axisStatusRouleauFoursIR.Stopping",
    statusStandStill:"Arp.Plc.Eclr/axisStatusRouleauFoursIR.StandStill",
    statusDiscreteMotion:"Arp.Plc.Eclr/axisStatusRouleauFoursIR.DiscreteMotion",
    statusContinuousMotion:"Arp.Plc.Eclr/axisStatusRouleauFoursIR.ContinuousMotion",
    statusSynchronizedMotion:"Arp.Plc.Eclr/axisStatusRouleauFoursIR.SynchronizedMotion",
    statusHoming:"Arp.Plc.Eclr/axisStatusRouleauFoursIR.Homing",

    gearInExecute:"",
    gearInRatioNumerator:"Arp.Plc.Eclr/ratioRouleauFoursIR",
    gearInVelocity:"",
    gearInAcceleration:"Arp.Plc.Eclr/accelerationMaitreFoursIR",
    gearInDeceleration:"Arp.Plc.Eclr/decelerationMaitreFoursIR",
    gearInInGear:"Arp.Plc.Eclr/gearInOutRouleauFoursIR.InGear",
    gearInBusy:"Arp.Plc.Eclr/gearInOutRouleauFoursIR.Busy",
    gearInActive:"Arp.Plc.Eclr/gearInOutRouleauFoursIR.Active",
    gearInCommandAborted:"Arp.Plc.Eclr/gearInOutRouleauFoursIR.CommandAborted",
    gearInError:"Arp.Plc.Eclr/gearInOutRouleauFoursIR.Error",
    gearInErrorID:"Arp.Plc.Eclr/gearInOutRouleauFoursIR.ErrorID",

    gearOutExecute:"",
    gearOutDone:"Arp.Plc.Eclr/gearOutOutRouleauFoursIR.Done",
    gearOutBusy:"Arp.Plc.Eclr/gearOutOutRouleauFoursIR.Busy",
    gearOutError:"Arp.Plc.Eclr/gearOutOutRouleauFoursIR.Error",
    gearOutErrorID:"Arp.Plc.Eclr/gearOutOutRouleauFoursIR.ErrorID",

    jogForward:"",
    jogReverse:"Arp.Plc.Eclr/reverseManuelRouleauFoursIR",
    jogVelocity:"Arp.Plc.Eclr/vitesseManuelRouleauFoursIR",
    jogAcceleration:"Arp.Plc.Eclr/accelerationManuelRouleauFoursIR",
    jogDeceleration:"Arp.Plc.Eclr/decelerationManuelRouleauFoursIR",
    jogInVelocity:"Arp.Plc.Eclr/jogOutRouleauFoursIR.InVelocity",
    jogDone:"Arp.Plc.Eclr/jogOutRouleauFoursIR.Done",
    jogBusy:"Arp.Plc.Eclr/jogOutRouleauFoursIR.Busy",
    jogError:"Arp.Plc.Eclr/jogOutRouleauFoursIR.Error",
    jogErrorID:"Arp.Plc.Eclr/jogOutRouleauFoursIR.ErrorID",

    resetAxisExecute:"Arp.Plc.Eclr/resetAxisRouleauFoursIR",
    resetAxisDone:"Arp.Plc.Eclr/resetAxisOutRouleauFoursIR.Done",
    resetAxisBusy:"Arp.Plc.Eclr/resetAxisOutRouleauFoursIR.Busy",
    resetAxisError:"Arp.Plc.Eclr/resetAxisOutRouleauFoursIR.Error",
    resetAxisErrorID:"Arp.Plc.Eclr/resetAxisOutRouleauFoursIR.ErrorID",

    resetEncodeurExecute:"Arp.Plc.Eclr/resetEncodeurRouleauFoursIR",
    resetEncodeurDone:"Arp.Plc.Eclr/resetEncodeurOutRouleauFoursIR.Done",
    resetEncodeurBusy:"Arp.Plc.Eclr/resetEncodeurOutRouleauFoursIR.Busy",
    resetEncodeurError:"Arp.Plc.Eclr/resetEncodeurOutRouleauFoursIR.Error",
    resetEncodeurErrorID:"Arp.Plc.Eclr/resetEncodeurOutRouleauFoursIR.ErrorID",

    stopAxisExecute:"Arp.Plc.Eclr/stopAxisRouleauFoursIR",
    stopAxisDone:"Arp.Plc.Eclr/stopOutputRouleauFoursIR.Done",
    stopAxisBusy:"Arp.Plc.Eclr/stopOutputRouleauFoursIR.Busy",
    stopAxisActive:"Arp.Plc.Eclr/stopOutputRouleauFoursIR.Active",
    stopAxisCommandAborted:"Arp.Plc.Eclr/stopOutputRouleauFoursIR.CommandAborted",
    stopAxisError:"Arp.Plc.Eclr/stopOutputRouleauFoursIR.Error",
    stopAxisErrorID:"Arp.Plc.Eclr/stopOutputRouleauFoursIR.ErrorID",

    rebootServoExecute:"Arp.Plc.Eclr/rebootServoRouleauFoursIR",
    rebootServoDone:"Arp.Plc.Eclr/rebootServoOutRouleauFoursIR.Done",
    rebootServoBusy:"Arp.Plc.Eclr/rebootServoOutRouleauFoursIR.Busy",
    rebootServoError:"Arp.Plc.Eclr/rebootServoOutRouleauFoursIR.Error",
    rebootServoErrorID:"Arp.Plc.Eclr/rebootServoOutRouleauFoursIR.ErrorID",

    valuePosition:"Arp.Plc.Eclr/axisValueRouleauFoursIR.Position",
    valueTorque:"Arp.Plc.Eclr/axisValueRouleauFoursIR.Torque",
    valueVelocity:"Arp.Plc.Eclr/axisValueRouleauFoursIR.Velocity",


}

const preAlimenteurFoursIR = {
    moteur: "PreAlimenteur IR",

    contactAuxiliaire: "Arp.Plc.Eclr/disjServoPreAlimenteursFoursIR",
    RDMContacteur: "Arp.Plc.Eclr/RDMServoPreAlimenteurFoursIR",
    erreurDisjoncteur: "Arp.Plc.Eclr/erreurDisjoncteurPreAlimenteurFoursIR",
    erreurContacteur: "Arp.Plc.Eclr/erreurContacteurPreAlimenteurFoursIR",

    axisControlEnable: "Arp.Plc.Eclr/startPreAlInfraRougeFoursIR",
    axisControlAlarmClear: "Arp.Plc.Eclr/acquitterPreAlInfraRougeFoursIR",
    axisControlStatus: "Arp.Plc.Eclr/axisControlOutPreAlimenteurInfraRougeFoursIR.Status",
    axisControlAxisAlarm: "Arp.Plc.Eclr/axisControlOutPreAlimenteurInfraRougeFoursIR.AxisAlarm",
    axisControlDriveWarning: "Arp.Plc.Eclr/axisControlOutPreAlimenteurInfraRougeFoursIR.DriveWarning",
    axisControlError: "Arp.Plc.Eclr/axisControlOutPreAlimenteurInfraRougeFoursIR.Error",
    axisControlErrorID: "Arp.Plc.Eclr/axisControlOutPreAlimenteurInfraRougeFoursIR.ErrorID",
    axisControlDriveWarningID: "Arp.Plc.Eclr/axisControlOutPreAlimenteurInfraRougeFoursIR.DriveWarningID",
    axisControlDriveAlarmID: "Arp.Plc.Eclr/axisControlOutPreAlimenteurInfraRougeFoursIR.DriveAlarmID",
    axisControlControlAlarmID: "Arp.Plc.Eclr/axisControlOutPreAlimenteurInfraRougeFoursIR.ControlAlarmID",

    statusValid:"Arp.Plc.Eclr/axisStatusPreAlimenteurInfraRougeFoursIR.Valid",
    statusBusy:"Arp.Plc.Eclr/axisStatusPreAlimenteurInfraRougeFoursIR.Busy",
    statusErrorStop:"Arp.Plc.Eclr/axisStatusPreAlimenteurInfraRougeFoursIR.ErrorStop",
    statusConstantVelocity:"Arp.Plc.Eclr/axisStatusPreAlimenteurInfraRougeFoursIR.ConstantVelocity",
    statusAccelerating:"Arp.Plc.Eclr/axisStatusPreAlimenteurInfraRougeFoursIR.Accelerating",
    statusDecelerating:"Arp.Plc.Eclr/axisStatusPreAlimenteurInfraRougeFoursIR.Decelerating",
    statusError:"Arp.Plc.Eclr/axisStatusPreAlimenteurInfraRougeFoursIR.Error",
    statusErrorID:"Arp.Plc.Eclr/axisStatusPreAlimenteurInfraRougeFoursIR.ErrorID",
    statusDisable:"Arp.Plc.Eclr/axisStatusPreAlimenteurInfraRougeFoursIR.Disable",
    statusStopping:"Arp.Plc.Eclr/axisStatusPreAlimenteurInfraRougeFoursIR.Stopping",
    statusStandStill:"Arp.Plc.Eclr/axisStatusPreAlimenteurInfraRougeFoursIR.StandStill",
    statusDiscreteMotion:"Arp.Plc.Eclr/axisStatusPreAlimenteurInfraRougeFoursIR.DiscreteMotion",
    statusContinuousMotion:"Arp.Plc.Eclr/axisStatusPreAlimenteurInfraRougeFoursIR.ContinuousMotion",
    statusSynchronizedMotion:"Arp.Plc.Eclr/axisStatusPreAlimenteurInfraRougeFoursIR.SynchronizedMotion",
    statusHoming:"Arp.Plc.Eclr/axisStatusPreAlimenteurInfraRougeFoursIR.Homing",

    gearInExecute:"",
    gearInRatioNumerator:"Arp.Plc.Eclr/ratioPreAlInfraRougeFoursIR",
    gearInVelocity:"",
    gearInAcceleration:"Arp.Plc.Eclr/accelerationMaitreFoursIR",
    gearInDeceleration:"Arp.Plc.Eclr/decelerationMaitreFoursIR",
    gearInInGear:"Arp.Plc.Eclr/gearInOutPreAlimenteurInfraRougeFoursIR.InGear",
    gearInBusy:"Arp.Plc.Eclr/gearInOutPreAlimenteurInfraRougeFoursIR.Busy",
    gearInActive:"Arp.Plc.Eclr/gearInOutPreAlimenteurInfraRougeFoursIR.Active",
    gearInCommandAborted:"Arp.Plc.Eclr/gearInOutPreAlimenteurInfraRougeFoursIR.CommandAborted",
    gearInError:"Arp.Plc.Eclr/gearInOutPreAlimenteurInfraRougeFoursIR.Error",
    gearInErrorID:"Arp.Plc.Eclr/gearInOutPreAlimenteurInfraRougeFoursIR.ErrorID",

    gearOutExecute:"",
    gearOutDone:"Arp.Plc.Eclr/gearOutOutPreAlimenteurInfraRougeFoursIR.Done",
    gearOutBusy:"Arp.Plc.Eclr/gearOutOutPreAlimenteurInfraRougeFoursIR.Busy",
    gearOutError:"Arp.Plc.Eclr/gearOutOutPreAlimenteurInfraRougeFoursIR.Error",
    gearOutErrorID:"Arp.Plc.Eclr/gearOutOutPreAlimenteurInfraRougeFoursIR.ErrorID",

    jogForward:"",
    jogReverse:"Arp.Plc.Eclr/reverseManuelPreAlInfraRougeFoursIR",
    jogVelocity:"Arp.Plc.Eclr/vitesseManuelPreAlInfraRougeFoursIR",
    jogAcceleration:"Arp.Plc.Eclr/accelerationManuelPreAlInfraRougeFoursIR",
    jogDeceleration:"Arp.Plc.Eclr/decelerationManuelPreAlInfraRougeFoursIR",
    jogInVelocity:"Arp.Plc.Eclr/jogOutPreAlimenteurInfraRougeFoursIR.InVelocity",
    jogDone:"Arp.Plc.Eclr/jogOutPreAlimenteurInfraRougeFoursIR.Done",
    jogBusy:"Arp.Plc.Eclr/jogOutPreAlimenteurInfraRougeFoursIR.Busy",
    jogError:"Arp.Plc.Eclr/jogOutPreAlimenteurInfraRougeFoursIR.Error",
    jogErrorID:"Arp.Plc.Eclr/jogOutPreAlimenteurInfraRougeFoursIR.ErrorID",

    resetAxisExecute:"Arp.Plc.Eclr/resetAxisPreAlInfraRougeFoursIR",
    resetAxisDone:"Arp.Plc.Eclr/resetAxisOutPreAlimenteurInfraRougeFoursIR.Done",
    resetAxisBusy:"Arp.Plc.Eclr/resetAxisOutPreAlimenteurInfraRougeFoursIR.Busy",
    resetAxisError:"Arp.Plc.Eclr/resetAxisOutPreAlimenteurInfraRougeFoursIR.Error",
    resetAxisErrorID:"Arp.Plc.Eclr/resetAxisOutPreAlimenteurInfraRougeFoursIR.ErrorID",

    resetEncodeurExecute:"Arp.Plc.Eclr/resetEncodeurPreAlInfraRougeFoursIR",
    resetEncodeurDone:"Arp.Plc.Eclr/resetEncodeurOutPreAlimenteurInfraRougeFoursIR.Done",
    resetEncodeurBusy:"Arp.Plc.Eclr/resetEncodeurOutPreAlimenteurInfraRougeFoursIR.Busy",
    resetEncodeurError:"Arp.Plc.Eclr/resetEncodeurOutPreAlimenteurInfraRougeFoursIR.Error",
    resetEncodeurErrorID:"Arp.Plc.Eclr/resetEncodeurOutPreAlimenteurInfraRougeFoursIR.ErrorID",

    stopAxisExecute:"Arp.Plc.Eclr/stopAxisPreAlInfraRougeFoursIR",
    stopAxisDone:"Arp.Plc.Eclr/stopOutputPreAlimenteurInfraRougeFoursIR.Done",
    stopAxisBusy:"Arp.Plc.Eclr/stopOutputPreAlimenteurInfraRougeFoursIR.Busy",
    stopAxisActive:"Arp.Plc.Eclr/stopOutputPreAlimenteurInfraRougeFoursIR.Active",
    stopAxisCommandAborted:"Arp.Plc.Eclr/stopOutputPreAlimenteurInfraRougeFoursIR.CommandAborted",
    stopAxisError:"Arp.Plc.Eclr/stopOutputPreAlimenteurInfraRougeFoursIR.Error",
    stopAxisErrorID:"Arp.Plc.Eclr/stopOutputPreAlimenteurInfraRougeFoursIR.ErrorID",

    rebootServoExecute:"Arp.Plc.Eclr/rebootServoPreAlInfraRougeFoursIR",
    rebootServoDone:"Arp.Plc.Eclr/rebootServoOutPreAlimenteurInfraRougeFoursIR.Done",
    rebootServoBusy:"Arp.Plc.Eclr/rebootServoOutPreAlimenteurInfraRougeFoursIR.Busy",
    rebootServoError:"Arp.Plc.Eclr/rebootServoOutPreAlimenteurInfraRougeFoursIR.Error",
    rebootServoErrorID:"Arp.Plc.Eclr/rebootServoOutPreAlimenteurInfraRougeFoursIR.ErrorID",

    valuePosition:"Arp.Plc.Eclr/axisValuePreAlimenteurInfraRougeFoursIR.Position",
    valueTorque:"Arp.Plc.Eclr/axisValuePreAlimenteurInfraRougeFoursIR.Torque",
    valueVelocity:"Arp.Plc.Eclr/axisValuePreAlimenteurInfraRougeFoursIR.Velocity",

}

const rouleauFour2 = {
    moteur: "Rouleau Four 2",

    contactAuxiliaire: "Arp.Plc.Eclr/disjServoFours",
    RDMContacteur: "Arp.Plc.Eclr/RDMServoRouleauxFours",
    erreurDisjoncteur: "Arp.Plc.Eclr/erreurDisjoncteurRouleauxFours",
    erreurContacteur: "Arp.Plc.Eclr/erreurContacteurRouleauxFours",

    axisControlEnable: "Arp.Plc.Eclr/startRouleauFour2",
    axisControlAlarmClear: "Arp.Plc.Eclr/acquitterRouleauFour2",
    axisControlStatus: "Arp.Plc.Eclr/axisControlOutRouleauFour2.Status",
    axisControlAxisAlarm: "Arp.Plc.Eclr/axisControlOutRouleauFour2.AxisAlarm",
    axisControlDriveWarning: "Arp.Plc.Eclr/axisControlOutRouleauFour2.DriveWarning",
    axisControlError: "Arp.Plc.Eclr/axisControlOutRouleauFour2.Error",
    axisControlErrorID: "Arp.Plc.Eclr/axisControlOutRouleauFour2.ErrorID",
    axisControlDriveWarningID: "Arp.Plc.Eclr/axisControlOutRouleauFour2.DriveWarningID",
    axisControlDriveAlarmID: "Arp.Plc.Eclr/axisControlOutRouleauFour2.DriveAlarmID",
    axisControlControlAlarmID: "Arp.Plc.Eclr/axisControlOutRouleauFour2.ControlAlarmID",

    statusValid: "Arp.Plc.Eclr/axisStatusRouleauFour2.Valid",
    statusBusy: "Arp.Plc.Eclr/axisStatusRouleauFour2.Busy",
    statusErrorStop: "Arp.Plc.Eclr/axisStatusRouleauFour2.ErrorStop",
    statusConstantVelocity: "Arp.Plc.Eclr/axisStatusRouleauFour2.ConstantVelocity",
    statusAccelerating: "Arp.Plc.Eclr/axisStatusRouleauFour2.Accelerating",
    statusDecelerating: "Arp.Plc.Eclr/axisStatusRouleauFour2.Decelerating",
    statusError: "Arp.Plc.Eclr/axisStatusRouleauFour2.Error",
    statusErrorID: "Arp.Plc.Eclr/axisStatusRouleauFour2.ErrorID",
    statusDisable: "Arp.Plc.Eclr/axisStatusRouleauFour2.Disable",
    statusStopping: "Arp.Plc.Eclr/axisStatusRouleauFour2.Stopping",
    statusStandStill: "Arp.Plc.Eclr/axisStatusRouleauFour2.StandStill",
    statusDiscreteMotion: "Arp.Plc.Eclr/axisStatusRouleauFour2.DiscreteMotion",
    statusContinuousMotion: "Arp.Plc.Eclr/axisStatusRouleauFour2.ContinuousMotion",
    statusSynchronizedMotion: "Arp.Plc.Eclr/axisStatusRouleauFour2.SynchronizedMotion",
    statusHoming: "Arp.Plc.Eclr/axisStatusRouleauFour2.Homing",

    gearInExecute:"",
    gearInRatioNumerator: "Arp.Plc.Eclr/ratioRouleauFour2",
    gearInVelocity:"",
    gearInAcceleration: "Arp.Plc.Eclr/accelerationMaitreFour2",
    gearInDeceleration: "Arp.Plc.Eclr/decelerationMaitreFour2",
    gearInInGear: "Arp.Plc.Eclr/gearInOutRouleauFour2.InGear",
    gearInBusy: "Arp.Plc.Eclr/gearInOutRouleauFour2.Busy",
    gearInActive: "Arp.Plc.Eclr/gearInOutRouleauFour2.Active",
    gearInCommandAborted: "Arp.Plc.Eclr/gearInOutRouleauFour2.CommandAborted",
    gearInError: "Arp.Plc.Eclr/gearInOutRouleauFour2.Error",
    gearInErrorID: "Arp.Plc.Eclr/gearInOutRouleauFour2.ErrorID",

    gearOutExecute:"",
    gearOutDone: "Arp.Plc.Eclr/gearOutOutRouleauFour2.Done",
    gearOutBusy: "Arp.Plc.Eclr/gearOutOutRouleauFour2.Busy",
    gearOutError: "Arp.Plc.Eclr/gearOutOutRouleauFour2.Error",
    gearOutErrorID: "Arp.Plc.Eclr/gearOutOutRouleauFour2.ErrorID",

    jogForward: "",
    jogReverse: "Arp.Plc.Eclr/reverseManuelRouleauFour2",
    jogVelocity: "Arp.Plc.Eclr/vitesseManuelRouleauFour2",
    jogAcceleration: "Arp.Plc.Eclr/accelerationManuelRouleauFour2",
    jogDeceleration: "Arp.Plc.Eclr/decelerationManuelRouleauFour2",
    jogInVelocity: "Arp.Plc.Eclr/jogOutRouleauFour2.InVelocity",
    jogDone: "Arp.Plc.Eclr/jogOutRouleauFour2.Done",
    jogBusy: "Arp.Plc.Eclr/jogOutRouleauFour2.Busy",
    jogError: "Arp.Plc.Eclr/jogOutRouleauFour2.Error",
    jogErrorID: "Arp.Plc.Eclr/jogOutRouleauFour2.ErrorID",

    resetAxisExecute: "Arp.Plc.Eclr/resetAxisRouleauFour2",
    resetAxisDone: "Arp.Plc.Eclr/resetAxisOutRouleauFour2.Done",
    resetAxisBusy: "Arp.Plc.Eclr/resetAxisOutRouleauFour2.Busy",
    resetAxisError: "Arp.Plc.Eclr/resetAxisOutRouleauFour2.Error",
    resetAxisErrorID: "Arp.Plc.Eclr/resetAxisOutRouleauFour2.ErrorID",

    resetEncodeurExecute: "Arp.Plc.Eclr/resetEncodeurRouleauFour2",
    resetEncodeurDone: "Arp.Plc.Eclr/resetEncodeurOutRouleauFour2.Done",
    resetEncodeurBusy: "Arp.Plc.Eclr/resetEncodeurOutRouleauFour2.Busy",
    resetEncodeurError: "Arp.Plc.Eclr/resetEncodeurOutRouleauFour2.Error",
    resetEncodeurErrorID: "Arp.Plc.Eclr/resetEncodeurOutRouleauFour2.ErrorID",

    stopAxisExecute: "Arp.Plc.Eclr/stopAxisRouleauFour2",
    stopAxisDone: "Arp.Plc.Eclr/stopOutputRouleauFour2.Done",
    stopAxisBusy: "Arp.Plc.Eclr/stopOutputRouleauFour2.Busy",
    stopAxisActive: "Arp.Plc.Eclr/stopOutputRouleauFour2.Active",
    stopAxisCommandAborted: "Arp.Plc.Eclr/stopOutputRouleauFour2.CommandAborted",
    stopAxisError: "Arp.Plc.Eclr/stopOutputRouleauFour2.Error",
    stopAxisErrorID: "Arp.Plc.Eclr/stopOutputRouleauFour2.ErrorID",

    rebootServoExecute: "Arp.Plc.Eclr/rebootServoRouleauFour2",
    rebootServoDone: "Arp.Plc.Eclr/rebootServoOutRouleauFour2.Done",
    rebootServoBusy: "Arp.Plc.Eclr/rebootServoOutRouleauFour2.Busy",
    rebootServoError: "Arp.Plc.Eclr/rebootServoOutRouleauFour2.Error",
    rebootServoErrorID: "Arp.Plc.Eclr/rebootServoOutRouleauFour2.ErrorID",

    valuePosition: "Arp.Plc.Eclr/axisValueRouleauFour2.Position",
    valueTorque: "Arp.Plc.Eclr/axisValueRouleauFour2.Torque",
    valueVelocity: "Arp.Plc.Eclr/axisValueRouleauFour2.Velocity",

}

const deposeFilsFour2 = {
    moteur:"Depose Fils Four 2",

    contactAuxiliaire: "Arp.Plc.Eclr/disjServoFours",
    RDMContacteur: "Arp.Plc.Eclr/RDMServoDeposeFilsFours",
    erreurDisjoncteur: "Arp.Plc.Eclr/erreurDisjoncteurDeposeFilsFours",
    erreurContacteur: "Arp.Plc.Eclr/erreurContacteurDeposeFilsFours",

    axisControlEnable: "Arp.Plc.Eclr/startDeposeFilsFour2",
    axisControlAlarmClear: "Arp.Plc.Eclr/acquitterDeposeFilsFour2",
    axisControlStatus: "Arp.Plc.Eclr/axisControlOutDeposeFilsFour2.Status",
    axisControlAxisAlarm: "Arp.Plc.Eclr/axisControlOutDeposeFilsFour2.AxisAlarm",
    axisControlDriveWarning: "Arp.Plc.Eclr/axisControlOutDeposeFilsFour2.DriveWarning",
    axisControlError: "Arp.Plc.Eclr/axisControlOutDeposeFilsFour2.Error",
    axisControlErrorID: "Arp.Plc.Eclr/axisControlOutDeposeFilsFour2.ErrorID",
    axisControlDriveWarningID: "Arp.Plc.Eclr/axisControlOutDeposeFilsFour2.DriveWarningID",
    axisControlDriveAlarmID: "Arp.Plc.Eclr/axisControlOutDeposeFilsFour2.DriveAlarmID",
    axisControlControlAlarmID: "Arp.Plc.Eclr/axisControlOutDeposeFilsFour2.ControlAlarmID",

    statusValid: "Arp.Plc.Eclr/axisStatusDeposeFilsFour2.Valid",
    statusBusy: "Arp.Plc.Eclr/axisStatusDeposeFilsFour2.Busy",
    statusErrorStop: "Arp.Plc.Eclr/axisStatusDeposeFilsFour2.ErrorStop",
    statusConstantVelocity: "Arp.Plc.Eclr/axisStatusDeposeFilsFour2.ConstantVelocity",
    statusAccelerating: "Arp.Plc.Eclr/axisStatusDeposeFilsFour2.Accelerating",
    statusDecelerating: "Arp.Plc.Eclr/axisStatusDeposeFilsFour2.Decelerating",
    statusError: "Arp.Plc.Eclr/axisStatusDeposeFilsFour2.Error",
    statusErrorID: "Arp.Plc.Eclr/axisStatusDeposeFilsFour2.ErrorID",
    statusDisable: "Arp.Plc.Eclr/axisStatusDeposeFilsFour2.Disable",
    statusStopping: "Arp.Plc.Eclr/axisStatusDeposeFilsFour2.Stopping",
    statusStandStill: "Arp.Plc.Eclr/axisStatusDeposeFilsFour2.StandStill",
    statusDiscreteMotion: "Arp.Plc.Eclr/axisStatusDeposeFilsFour2.DiscreteMotion",
    statusContinuousMotion: "Arp.Plc.Eclr/axisStatusDeposeFilsFour2.ContinuousMotion",
    statusSynchronizedMotion: "Arp.Plc.Eclr/axisStatusDeposeFilsFour2.SynchronizedMotion",
    statusHoming: "Arp.Plc.Eclr/axisStatusDeposeFilsFour2.Homing",

    gearInExecute:"",
    gearInRatioNumerator:"Arp.Plc.Eclr/ratioDeposeFilsFour2",
    gearInVelocity:"",
    gearInAcceleration:"Arp.Plc.Eclr/accelerationMaitreFour2",
    gearInDeceleration:"Arp.Plc.Eclr/decelerationMaitreFour2",
    gearInInGear:"Arp.Plc.Eclr/gearInOutDeposeFilsFour2.InGear",
    gearInBusy:"Arp.Plc.Eclr/gearInOutDeposeFilsFour2.Busy",
    gearInActive:"Arp.Plc.Eclr/gearInOutDeposeFilsFour2.Active",
    gearInCommandAborted:"Arp.Plc.Eclr/gearInOutDeposeFilsFour2.CommandAborted",
    gearInError:"Arp.Plc.Eclr/gearInOutDeposeFilsFour2.Error",
    gearInErrorID:"Arp.Plc.Eclr/gearInOutDeposeFilsFour2.ErrorID",

    gearOutExecute:"",
    gearOutDone: "Arp.Plc.Eclr/gearOutOutDeposeFilsFour2.Done",
    gearOutBusy: "Arp.Plc.Eclr/gearOutOutDeposeFilsFour2.Busy",
    gearOutError: "Arp.Plc.Eclr/gearOutOutDeposeFilsFour2.Error",
    gearOutErrorID: "Arp.Plc.Eclr/gearOutOutDeposeFilsFour2.ErrorID",

    jogForward:"",
    jogReverse: "Arp.Plc.Eclr/reverseManuelDeposeFilsFour2",
    jogVelocity: "Arp.Plc.Eclr/vitesseManuelDeposeFilsFour2",
    jogAcceleration: "Arp.Plc.Eclr/accelerationManuelDeposeFilsFour2",
    jogDeceleration: "Arp.Plc.Eclr/decelerationManuelDeposeFilsFour2",
    jogInVelocity: "Arp.Plc.Eclr/jogOutDeposeFilsFour2.InVelocity",
    jogDone: "Arp.Plc.Eclr/jogOutDeposeFilsFour2.Done",
    jogBusy: "Arp.Plc.Eclr/jogOutDeposeFilsFour2.Busy",
    jogError: "Arp.Plc.Eclr/jogOutDeposeFilsFour2.Error",
    jogErrorID: "Arp.Plc.Eclr/jogOutDeposeFilsFour2.ErrorID",

    resetAxisExecute: "Arp.Plc.Eclr/resetAxisDeposeFilsFour2",
    resetAxisDone: "Arp.Plc.Eclr/resetAxisOutDeposeFilsFour2.Done",
    resetAxisBusy: "Arp.Plc.Eclr/resetAxisOutDeposeFilsFour2.Busy",
    resetAxisError: "Arp.Plc.Eclr/resetAxisOutDeposeFilsFour2.Error",
    resetAxisErrorID: "Arp.Plc.Eclr/resetAxisOutDeposeFilsFour2.ErrorID",

    resetEncodeurExecute:"Arp.Plc.Eclr/resetEncodeurDeposeFilsFour2",
    resetEncodeurDone:"Arp.Plc.Eclr/resetEncodeurOutDeposeFilsFour2.Done",
    resetEncodeurBusy:"Arp.Plc.Eclr/resetEncodeurOutDeposeFilsFour2.Busy",
    resetEncodeurError:"Arp.Plc.Eclr/resetEncodeurOutDeposeFilsFour2.Error",
    resetEncodeurErrorID:"Arp.Plc.Eclr/resetEncodeurOutDeposeFilsFour2.ErrorID",

    stopAxisExecute: "Arp.Plc.Eclr/stopAxisDeposeFilsFour2",
    stopAxisDone: "Arp.Plc.Eclr/stopOutputDeposeFilsFour2.Done",
    stopAxisBusy: "Arp.Plc.Eclr/stopOutputDeposeFilsFour2.Busy",
    stopAxisActive: "Arp.Plc.Eclr/stopOutputDeposeFilsFour2.Active",
    stopAxisCommandAborted: "Arp.Plc.Eclr/stopOutputDeposeFilsFour2.CommandAborted",
    stopAxisError: "Arp.Plc.Eclr/stopOutputDeposeFilsFour2.Error",
    stopAxisErrorID: "Arp.Plc.Eclr/stopOutputDeposeFilsFour2.ErrorID",

    rebootServoExecute: "Arp.Plc.Eclr/rebootServoDeposeFilsFour2",
    rebootServoDone: "Arp.Plc.Eclr/rebootServoOutDeposeFilsFour2.Done",
    rebootServoBusy: "Arp.Plc.Eclr/rebootServoOutDeposeFilsFour2.Busy",
    rebootServoError: "Arp.Plc.Eclr/rebootServoOutDeposeFilsFour2.Error",
    rebootServoErrorID: "Arp.Plc.Eclr/rebootServoOutDeposeFilsFour2.ErrorID",

    valuePosition: "Arp.Plc.Eclr/axisValueDeposeFilsFour2.Position",
    valueTorque: "Arp.Plc.Eclr/axisValueDeposeFilsFour2.Torque",
    valueVelocity: "Arp.Plc.Eclr/axisValueDeposeFilsFour2.Velocity",


}

const tapisFour2 = {
    moteur:"Tapis Four 2",

    contactAuxiliaire: "Arp.Plc.Eclr/disjServoFours",
    RDMContacteur: "Arp.Plc.Eclr/RDMServoTapisFours",
    erreurDisjoncteur: "Arp.Plc.Eclr/erreurDisjoncteurTapisFours",
    erreurContacteur: "Arp.Plc.Eclr/erreurContacteurTapisFours",

    axisControlEnable:"Arp.Plc.Eclr/startTapisFour2",
    axisControlAlarmClear:"Arp.Plc.Eclr/acquitterTapisFour2",
    axisControlStatus:"Arp.Plc.Eclr/axisControlOutTapisFour2.Status",
    axisControlAxisAlarm:"Arp.Plc.Eclr/axisControlOutTapisFour2.AxisAlarm",
    axisControlDriveWarning:"Arp.Plc.Eclr/axisControlOutTapisFour2.DriveWarning",
    axisControlError:"Arp.Plc.Eclr/axisControlOutTapisFour2.Error",
    axisControlErrorID:"Arp.Plc.Eclr/axisControlOutTapisFour2.ErrorID",
    axisControlDriveWarningID:"Arp.Plc.Eclr/axisControlOutTapisFour2.DriveWarningID",
    axisControlDriveAlarmID:"Arp.Plc.Eclr/axisControlOutTapisFour2.DriveAlarmID",
    axisControlControlAlarmID:"Arp.Plc.Eclr/axisControlOutTapisFour2.ControlAlarmID",

    statusValid:"Arp.Plc.Eclr/axisStatusTapisFour2.Valid",
    statusBusy:"Arp.Plc.Eclr/axisStatusTapisFour2.Busy",
    statusErrorStop:"Arp.Plc.Eclr/axisStatusTapisFour2.ErrorStop",
    statusConstantVelocity:"Arp.Plc.Eclr/axisStatusTapisFour2.ConstantVelocity",
    statusAccelerating:"Arp.Plc.Eclr/axisStatusTapisFour2.Accelerating",
    statusDecelerating:"Arp.Plc.Eclr/axisStatusTapisFour2.Decelerating",
    statusError:"Arp.Plc.Eclr/axisStatusTapisFour2.Error",
    statusErrorID:"Arp.Plc.Eclr/axisStatusTapisFour2.ErrorID",
    statusDisable:"Arp.Plc.Eclr/axisStatusTapisFour2.Disable",
    statusStopping:"Arp.Plc.Eclr/axisStatusTapisFour2.Stopping",
    statusStandStill:"Arp.Plc.Eclr/axisStatusTapisFour2.StandStill",
    statusDiscreteMotion:"Arp.Plc.Eclr/axisStatusTapisFour2.DiscreteMotion",
    statusContinuousMotion:"Arp.Plc.Eclr/axisStatusTapisFour2.ContinuousMotion",
    statusSynchronizedMotion:"Arp.Plc.Eclr/axisStatusTapisFour2.SynchronizedMotion",
    statusHoming:"Arp.Plc.Eclr/axisStatusTapisFour2.Homing",

    gearInExecute:"",
    gearInRatioNumerator:"Arp.Plc.Eclr/ratioTapisFour2",
    gearInVelocity:"",
    gearInAcceleration:"Arp.Plc.Eclr/accelerationMaitreFour2",
    gearInDeceleration:"Arp.Plc.Eclr/decelerationMaitreFour2",
    gearInInGear:"Arp.Plc.Eclr/gearInOutTapisFour2.InGear",
    gearInBusy:"Arp.Plc.Eclr/gearInOutTapisFour2.Busy",
    gearInActive:"Arp.Plc.Eclr/gearInOutTapisFour2.Active",
    gearInCommandAborted:"Arp.Plc.Eclr/gearInOutTapisFour2.CommandAborted",
    gearInError:"Arp.Plc.Eclr/gearInOutTapisFour2.Error",
    gearInErrorID:"Arp.Plc.Eclr/gearInOutTapisFour2.ErrorID",

    gearOutExecute:"",
    gearOutDone:"Arp.Plc.Eclr/gearOutOutTapisFour2.Done",
    gearOutBusy:"Arp.Plc.Eclr/gearOutOutTapisFour2.Busy",
    gearOutError:"Arp.Plc.Eclr/gearOutOutTapisFour2.Error",
    gearOutErrorID:"Arp.Plc.Eclr/gearOutOutTapisFour2.ErrorID",

    jogForward:"",
    jogReverse:"Arp.Plc.Eclr/reverseManuelTapisFour2",
    jogVelocity:"Arp.Plc.Eclr/vitesseManuelTapisFour2",
    jogAcceleration:"Arp.Plc.Eclr/accelerationManuelTapisFour2",
    jogDeceleration:"Arp.Plc.Eclr/decelerationManuelTapisFour2",
    jogInVelocity:"Arp.Plc.Eclr/jogOutTapisFour2.InVelocity",
    jogDone:"Arp.Plc.Eclr/jogOutTapisFour2.Done",
    jogBusy:"Arp.Plc.Eclr/jogOutTapisFour2.Busy",
    jogError:"Arp.Plc.Eclr/jogOutTapisFour2.Error",
    jogErrorID:"Arp.Plc.Eclr/jogOutTapisFour2.ErrorID",

    resetAxisExecute:"Arp.Plc.Eclr/resetAxisTapisFour2",
    resetAxisDone:"Arp.Plc.Eclr/resetAxisOutTapisFour2.Done",
    resetAxisBusy:"Arp.Plc.Eclr/resetAxisOutTapisFour2.Busy",
    resetAxisError:"Arp.Plc.Eclr/resetAxisOutTapisFour2.Error",
    resetAxisErrorID:"Arp.Plc.Eclr/resetAxisOutTapisFour2.ErrorID",

    resetEncodeurExecute:"Arp.Plc.Eclr/resetEncodeurTapisFour2",
    resetEncodeurDone:"Arp.Plc.Eclr/resetEncodeurOutTapisFour2.Done",
    resetEncodeurBusy:"Arp.Plc.Eclr/resetEncodeurOutTapisFour2.Busy",
    resetEncodeurError:"Arp.Plc.Eclr/resetEncodeurOutTapisFour2.Error",
    resetEncodeurErrorID:"Arp.Plc.Eclr/resetEncodeurOutTapisFour2.ErrorID",

    stopAxisExecute:"Arp.Plc.Eclr/stopAxisTapisFour2",
    stopAxisDone:"Arp.Plc.Eclr/stopOutputTapisFour2.Done",
    stopAxisBusy:"Arp.Plc.Eclr/stopOutputTapisFour2.Busy",
    stopAxisActive:"Arp.Plc.Eclr/stopOutputTapisFour2.Active",
    stopAxisCommandAborted:"Arp.Plc.Eclr/stopOutputTapisFour2.CommandAborted",
    stopAxisError:"Arp.Plc.Eclr/stopOutputTapisFour2.Error",
    stopAxisErrorID:"Arp.Plc.Eclr/stopOutputTapisFour2.ErrorID",

    rebootServoExecute:"Arp.Plc.Eclr/rebootServoTapisFour2",
    rebootServoDone:"Arp.Plc.Eclr/rebootServoOutTapisFour2.Done",
    rebootServoBusy:"Arp.Plc.Eclr/rebootServoOutTapisFour2.Busy",
    rebootServoError:"Arp.Plc.Eclr/rebootServoOutTapisFour2.Error",
    rebootServoErrorID:"Arp.Plc.Eclr/rebootServoOutTapisFour2.ErrorID",

    valuePosition:"Arp.Plc.Eclr/axisValueTapisFour2.Position",
    valueTorque:"Arp.Plc.Eclr/axisValueTapisFour2.Torque",
    valueVelocity:"Arp.Plc.Eclr/axisValueTapisFour2.Velocity",
}

const bobinoir ={
    moteur:"Bobinoir",
}

const trancanage ={
    moteur:"Trancanage",
}

const motorData = [
    rouleauFour1,
    deposeFilsFour1,
    tapisFour1,
    preAlimenteurImpression,
    rouleauFoursIR,
    preAlimenteurFoursIR,
    rouleauFour2,
    deposeFilsFour2,
    tapisFour2
]
