const ventilationFour1 = {
    motor:"Four 1",
    xRunning:"Arp.Plc.Eclr/variateurFour1.sts.xRunning",
    xError:"Arp.Plc.Eclr/variateurFour1.sts.xError",
    ActualVelo:"Arp.Plc.Eclr/variateurFour1.sts.ActualVelo",
    sState:"Arp.Plc.Eclr/variateurFour1.sts.sState",
    xReadyToSwitchOn:"Arp.Plc.Eclr/variateurFour1.sts.xReadyToSwitchOn",
    xSwitchedOn:"Arp.Plc.Eclr/variateurFour1.sts.xSwitchedOn",
    xOperationEnabled:"Arp.Plc.Eclr/variateurFour1.sts.xOperationEnabled",
    xFault:"Arp.Plc.Eclr/variateurFour1.sts.xFault",
    xVoltageEnabled:"Arp.Plc.Eclr/variateurFour1.sts.xVoltageEnabled",
    xQuickStop:"Arp.Plc.Eclr/variateurFour1.sts.xQuickStop",
    xSwitchOnDisabled:"Arp.Plc.Eclr/variateurFour1.sts.xSwitchOnDisabled",
    xWarning:"Arp.Plc.Eclr/variateurFour1.sts.xWarning",
    xAtVelo:"Arp.Plc.Eclr/variateurFour1.sts.xAtVelo",
    xRemote:"Arp.Plc.Eclr/variateurFour1.sts.xRemote",
    xRun:"Arp.Plc.Eclr/variateurFour1.cmd.xRun",
    xClear:"Arp.Plc.Eclr/variateurFour1.cmd.xClear",
    cmdVelo:"ns=6;s=Arp.Plc.Eclr/variateurFour1.Cmd.Velo",
    StsWord:"Arp.Plc.Eclr/variateurFour1.In.StsWord",
    VlControlEffort:"Arp.Plc.Eclr/variateurFour1.In.VlControlEffort",
    CtrlWord:"Arp.Plc.Eclr/variateurFour1.Out.CtrlWord",
    outVelo:"Arp.Plc.Eclr/variateurFour1.Out.Velo",
}
const ventilationFour2 = {
    motor:"Four 2",
    xRunning:"Arp.Plc.Eclr/variateurFour2.sts.xRunning",
    xError:"Arp.Plc.Eclr/variateurFour2.sts.xError",
    ActualVelo:"Arp.Plc.Eclr/variateurFour2.sts.ActualVelo",
    sState:"Arp.Plc.Eclr/variateurFour2.sts.sState",
    xReadyToSwitchOn:"Arp.Plc.Eclr/variateurFour2.sts.xReadyToSwitchOn",
    xSwitchedOn:"Arp.Plc.Eclr/variateurFour2.sts.xSwitchedOn",
    xOperationEnabled:"Arp.Plc.Eclr/variateurFour2.sts.xOperationEnabled",
    xFault:"Arp.Plc.Eclr/variateurFour2.sts.xFault",
    xVoltageEnabled:"Arp.Plc.Eclr/variateurFour2.sts.xVoltageEnabled",
    xQuickStop:"Arp.Plc.Eclr/variateurFour2.sts.xQuickStop",
    xSwitchOnDisabled:"Arp.Plc.Eclr/variateurFour2.sts.xSwitchOnDisabled",
    xWarning:"Arp.Plc.Eclr/variateurFour2.sts.xWarning",
    xAtVelo:"Arp.Plc.Eclr/variateurFour2.sts.xAtVelo",
    xRemote:"Arp.Plc.Eclr/variateurFour2.sts.xRemote",
    xRun:"Arp.Plc.Eclr/variateurFour2.cmd.xRun",
    xClear:"Arp.Plc.Eclr/variateurFour2.cmd.xClear",
    cmdVelo:"ns=6;s=Arp.Plc.Eclr/variateurFour2.Cmd.Velo",
    StsWord:"Arp.Plc.Eclr/variateurFour2.In.StsWord",
    VlControlEffort:"Arp.Plc.Eclr/variateurFour2.In.VlControlEffort",
    CtrlWord:"Arp.Plc.Eclr/variateurFour2.Out.CtrlWord",
    outVelo:"Arp.Plc.Eclr/variateurFour2.Out.Velo",
}
const extraction = {
    motor:"Extraction",
    xRunning:"Arp.Plc.Eclr/variateurExtraction.sts.xRunning",
    xError:"Arp.Plc.Eclr/variateurExtraction.sts.xError",
    ActualVelo:"Arp.Plc.Eclr/variateurExtraction.sts.ActualVelo",
    sState:"Arp.Plc.Eclr/variateurExtraction.sts.sState",
    xReadyToSwitchOn:"Arp.Plc.Eclr/variateurExtraction.sts.xReadyToSwitchOn",
    xSwitchedOn:"Arp.Plc.Eclr/variateurExtraction.sts.xSwitchedOn",
    xOperationEnabled:"Arp.Plc.Eclr/variateurExtraction.sts.xOperationEnabled",
    xFault:"Arp.Plc.Eclr/variateurExtraction.sts.xFault",
    xVoltageEnabled:"Arp.Plc.Eclr/variateurExtraction.sts.xVoltageEnabled",
    xQuickStop:"Arp.Plc.Eclr/variateurExtraction.sts.xQuickStop",
    xSwitchOnDisabled:"Arp.Plc.Eclr/variateurExtraction.sts.xSwitchOnDisabled",
    xWarning:"Arp.Plc.Eclr/variateurExtraction.sts.xWarning",
    xAtVelo:"Arp.Plc.Eclr/variateurExtraction.sts.xAtVelo",
    xRemote:"Arp.Plc.Eclr/variateurExtraction.sts.xRemote",
    xRun:"Arp.Plc.Eclr/variateurExtraction.cmd.xRun",
    xClear:"Arp.Plc.Eclr/variateurExtraction.cmd.xClear",
    cmdVelo:"ns=6;s=Arp.Plc.Eclr/variateurExtraction.Cmd.Velo",
    StsWord:"Arp.Plc.Eclr/variateurExtraction.In.StsWord",
    VlControlEffort:"Arp.Plc.Eclr/variateurExtraction.In.VlControlEffort",
    CtrlWord:"Arp.Plc.Eclr/variateurExtraction.Out.CtrlWord",
    outVelo:"Arp.Plc.Eclr/variateurExtraction.Out.Velo",
}
const ventilation = [
    ventilationFour1,
    ventilationFour2,
    extraction
]
const chauffeFour1 = {
    location:"Four 1",
    enable:"Arp.Plc.Eclr/startBCFour1",
    relaisStatique:"Arp.Plc.Eclr/relaisStatiqueFour1",
    consigne:"Arp.Plc.Eclr/consigneTemperatureFour1",
    disjoncteur:"Arp.Plc.Eclr/disjResistanceFour1",
    RDMCommutateur:"Arp.Plc.Eclr/RDMResistanceFour1",
    pt100BC:"Arp.Plc.Eclr/temperatureBCFour1",
    pt100Four:"Arp.Plc.Eclr/temperatureFour1",
    statusTemperature:"Arp.Plc.Eclr/statusTemperatureFour1",
    statusChauffe:"Arp.Plc.Eclr/statusChauffeFour1",
    temperatureOK:"Arp.Plc.Eclr/temperatureOKFour1",
    warning:"Arp.Plc.Eclr/warningChauffeFour1",
    error:"Arp.Plc.Eclr/errorChauffeFour1",
    chauffe:"Arp.Plc.Eclr/ordreChauffeFour1",
    commutateur:"Arp.Plc.Eclr/relaisContacteurRelaisStatiqueFour1",
}
const chauffeFour2 = {
    location:"Four 2",
    enable:"Arp.Plc.Eclr/startBCFour2",
    relaisStatique:"Arp.Plc.Eclr/relaisStatiqueFour2",
    consigne:"Arp.Plc.Eclr/consigneTemperatureFour2",
    disjoncteur:"Arp.Plc.Eclr/disjResistanceFour2",
    RDMCommutateur:"Arp.Plc.Eclr/RDMResistanceFour2",
    pt100BC:"Arp.Plc.Eclr/temperatureBCFour2",
    pt100Four:"Arp.Plc.Eclr/temperatureFour2",
    statusTemperature:"Arp.Plc.Eclr/statusTemperatureFour2",
    statusChauffe:"Arp.Plc.Eclr/statusChauffeFour2",
    temperatureOK:"Arp.Plc.Eclr/temperatureOKFour2",
    warning:"Arp.Plc.Eclr/warningChauffeFour2",
    error:"Arp.Plc.Eclr/errorChauffeFour2",
    chauffe:"Arp.Plc.Eclr/ordreChauffeFour2",
    commutateur:"Arp.Plc.Eclr/relaisContacteurRelaisStatiqueFour2",
}
const chauffe = [
    chauffeFour1,
    chauffeFour2
]
